version: '3.7'
services:

  docker_mongo:
    restart: always
    image: mongo:latest
    ports:
      - "127.0.0.1:27017:27017"

  docker_redis:
    restart: always
    image: redis:latest
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data

  webapp_next:
    restart: always
    build:
      context: webapp/
      args:
        - GOOGLE_KEYPATH=keyfile.json
        - SHORT_COMMIT_HASH=${SHORT_COMMIT_HASH}
        - NEXT_PUBLIC_NO_PAYMENT_REQUIRED=1
        - NEXT_PUBLIC_ENABLE_GOOGLE_OAUTH=
        - NEXT_PUBLIC_ENABLE_GITHUB_OAUTH=
        - POSTHOG_KEY=
    network_mode: host
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - docker_mongo
      - docker_redis
    environment:
      - NODE_ENV=development
      - DB_URL=mongodb://127.0.0.1:27017/test
      - REDIS_HOST=127.0.0.1
      - REDIS_PASS=
      - JWT_SECRET=changeme
      - COOKIE_SECRET=changeme
      - AGENT_BACKEND_SOCKET_TOKEN=changeme
      - PROJECT_ID=${PROJECT_ID}
      - FROM_EMAIL_ADDRESS=noreply@agentcloud.dev
      - URL_APP=http://127.0.0.1:3000
      - DEBUG=webapp:*
      - STRIPE_WEBHOOK_SECRET=
      - STRIPE_ACCOUNT_SECRET=
      - STRIPE_PRICE_ID=
      - NEXT_PUBLIC_NO_PAYMENT_REQUIRED=1
      - OAUTH_GITHUB_CLIENT_ID=
      - OAUTH_GITHUB_CLIENT_SECRET=
      - OAUTH_GOOGLE_CLIENT_ID=
      - OAUTH_GOOGLE_CLIENT_SECRET=
      - AIRBYTE_WEB_URL=http://127.0.0.1:8000
      - AIRBYTE_API_URL=http://127.0.0.1:8006
      - AIRBYTE_ADMIN_WORKSPACE_ID=${AIRBYTE_ADMIN_WORKSPACE_ID}
      - AIRBYTE_ADMIN_DESTINATION_ID=${AIRBYTE_ADMIN_DESTINATION_ID}
      - AIRBYTE_USERNAME=airbyte
      - AIRBYTE_PASSWORD=password
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME}

  agent_backend:
    restart: always
    build:
      context: agent-backend/
      args:
        - SHORT_COMMIT_HASH=${SHORT_COMMIT_HASH}
    ports:
      - '127.0.0.1:8080:8080'
    image: agent_backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - LOCAL=True
      - MAX_THREADS=50
      - OAI_CONFIG_LIST=/app/config/OAI_CONFIG_LIST.json
      - BASE_PATH=/app
      - SOCKET_URL=http://webapp_next:3000/
      - DB_URL=mongodb://docker_mongo:27017/test
      - REDIS_HOST=docker_redis
      - MONGO_DB_NAME=test
      - MAX_RETRIES=10
      - AGENT_BACKEND_SOCKET_TOKEN=changeme

  vector_db_proxy:
    restart: always
    build:
      context: vector-db-proxy/
      args:
        - SHORT_COMMIT_HASH=${SHORT_COMMIT_HASH}
    ports:
      - '127.0.0.1:8001:8001'
    image: vector_db_proxy
    environment:
      - HOST=0.0.0.0
      - PORT=8001
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_STREAM=streaming
      - RABBITMQ_EXCHANGE=agentcloud
      - RABBITMQ_ROUTING_KEY=key
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest

  qdrant:
    ports:
      - '127.0.0.1:6333:6333'
      - '127.0.0.1:6334:6334'
    image: qdrant/qdrant

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3
    network_mode: host

volumes:
  mongodb_data_container:
  redis_data:
