steps:
  # build the container image
  - name: "gcr.io/kaniko-project/executor:latest"
    id: "Build Docker image"
    env:
      - 'BUILD=$BUILD_ID'
      - 'PROJECT=$PROJECT_ID'
      - 'REV=$REVISION_ID'
    args:
      - --destination=gcr.io/$PROJECT_ID/vector-db:$BUILD_ID
      - --cache=true
      - --cache-ttl=96h
    # deploy container image to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    id: "Deploy Container to GKE"
    args:
      - run
      - --filename=kubernetes/dev/deployment.yaml
      - --image=gcr.io/$PROJECT_ID/vector-db:$BUILD_ID
      - --location=$_ZONE
      - --cluster=$_CLUSTER
timeout: '16000s'
options:
  machineType: 'E2_HIGHCPU_8'
