apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: webapp-cert-dev
  namespace: webapp-dev
spec:
  domains:
    - rapdev-app.getmonita.io
    - api.rapdev-app.getmonita.io
    - qdrant.rapdev-app.getmonita.io